// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFwr1unhLXvVoIlWKeOVkSLwTl8Krr4Cg',
    appId: '1:367896041087:web:323b4b246fd9c7aa66914a',
    messagingSenderId: '367896041087',
    projectId: 'situp-127fa',
    authDomain: 'situp-127fa.firebaseapp.com',
    storageBucket: 'situp-127fa.firebasestorage.app',
    measurementId: 'G-NDWSM8L798',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW85o1qf03-Mq33ziBiRYFaPFTBgn_pF0',
    appId: '1:367896041087:android:53ea8b767b86a72366914a',
    messagingSenderId: '367896041087',
    projectId: 'situp-127fa',
    storageBucket: 'situp-127fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWl_ct4D_NPsmG6KM2lfff__CLEibaaHI',
    appId: '1:367896041087:ios:298b1baeed9678f566914a',
    messagingSenderId: '367896041087',
    projectId: 'situp-127fa',
    storageBucket: 'situp-127fa.firebasestorage.app',
    iosBundleId: 'com.example.situp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWl_ct4D_NPsmG6KM2lfff__CLEibaaHI',
    appId: '1:367896041087:ios:298b1baeed9678f566914a',
    messagingSenderId: '367896041087',
    projectId: 'situp-127fa',
    storageBucket: 'situp-127fa.firebasestorage.app',
    iosBundleId: 'com.example.situp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFwr1unhLXvVoIlWKeOVkSLwTl8Krr4Cg',
    appId: '1:367896041087:web:c619585ad96a509066914a',
    messagingSenderId: '367896041087',
    projectId: 'situp-127fa',
    authDomain: 'situp-127fa.firebaseapp.com',
    storageBucket: 'situp-127fa.firebasestorage.app',
    measurementId: 'G-ZY471H1ZFW',
  );
}
